[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hub_py"
version = "0.0.1"
requires-python = ">=3.8"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]